const quotes = [
  {quote: "Commence chaque journée par te dire : Je vais rencontrer un indiscret, un ingrat, un insolent, un trompeur, un envieux, un égoïste.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Ce n’est pas parce que les choses sont difficiles que nous n’osons pas, c’est parce que nous n’osons pas qu’elles sont difficiles.", author: "Sénèque", work: "Lettres à Lucilius"},
  {quote: "Ce qui trouble les hommes, ce ne sont pas les choses, mais les jugements qu’ils portent sur les choses.", author: "Épictète", work: "Manuel"},
  {quote: "La difficulté montre ce que les hommes sont.", author: "Épictète", work: "Entretiens"},
  {quote: "La vie ce n’est pas d’attendre que l’orage passe, c’est d’apprendre à danser sous la pluie.", author: "Sénèque", work: "Lettres à Lucilius"},
  {quote: "N’attends pas que les événements arrivent comme tu le souhaites ; décide de vouloir ce qui arrive et tu seras heureux.", author: "Épictète", work: "Manuel"},
  {quote: "La vraie grandeur consiste à être maître de soi.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "On ne se baigne jamais deux fois dans le même fleuve.", author: "Héraclite", work: ""},
  {quote: "La plus grande richesse est de se contenter de peu.", author: "Épictète", work: ""},
  {quote: "Ce n’est pas la mort qu’il faut craindre, mais de n’avoir jamais commencé à vivre.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Il n’y a qu’un chemin vers le bonheur, c’est de cesser de s’inquiéter de ce qui ne dépend pas de nous.", author: "Épictète", work: ""},
  {quote: "Occupe-toi de toi-même, et tu t’occuperas bien des autres.", author: "Sénèque", work: ""},
  {quote: "Le bonheur de ta vie dépend de la qualité de tes pensées.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Il n’est rien de plus méprisable que de voir quelqu’un chercher à convaincre autrui de ce qu’il n’a pas lui-même mis en pratique.", author: "Sénèque", work: ""},
  {quote: "L’homme n’est troublé que par l’opinion qu’il a des choses.", author: "Épictète", work: "Manuel"},
  {quote: "La tranquillité vient de l’intérieur, ne la cherche pas à l’extérieur.", author: "Marc Aurèle", work: ""},
  {quote: "Ce qui ne dépend pas de moi, je le laisse aller.", author: "Épictète", work: ""},
  {quote: "Accepte tout ce qui t’arrive, même les douleurs les plus cruelles, et tu seras invincible.", author: "Sénèque", work: ""},
  {quote: "La raison ne veut rien qui soit en dehors de sa puissance.", author: "Marc Aurèle", work: ""},
  {quote: "Celui qui ne sait pas se contenter de peu ne sera jamais content de rien.", author: "Épicure", work: ""},
  {quote: "Le premier fondement de la philosophie est la conscience de notre faiblesse.", author: "Épictète", work: ""},
  {quote: "La seule chose qui soit en notre pouvoir, ce sont nos pensées.", author: "Épictète", work: ""},
  {quote: "Ce que tu fais aujourd’hui est important, parce que tu échanges un jour de ta vie contre cela.", author: "Marc Aurèle", work: ""},
  {quote: "Ce n’est pas l’homme qui a trop peu, mais celui qui désire plus, qui est pauvre.", author: "Sénèque", work: ""},
  {quote: "La meilleure vengeance est de ne pas ressembler à celui qui t’a offensé.", author: "Marc Aurèle", work: ""},
  {quote: "La difficulté n’est qu’un mot, il n’exprime rien de réel.", author: "Sénèque", work: ""},
  {quote: "Rien n’est pénible si tu le fais de bon cœur.", author: "Sénèque", work: ""},
  {quote: "Ce qui importe, ce n’est pas ce qui t’arrive, mais la manière dont tu le prends.", author: "Épictète", work: ""},
  {quote: "Nous avons deux oreilles et une bouche afin d’écouter deux fois plus que nous ne parlons.", author: "Zénon de Cition", work: ""},
  {quote: "La vertu seule suffit au bonheur.", author: "Sénèque", work: ""},
  {quote: "Ne gaspille plus de temps à discuter de ce que devrait être un homme bon. Sois-en un !", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Il n’y a pas de vent favorable pour celui qui ne sait pas où il va.", author: "Sénèque", work: ""},
  {quote: "Qui vit en harmonie avec lui-même vit en harmonie avec l’univers.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Le désir est une souffrance d’avance.", author: "Sénèque", work: ""},
  {quote: "Avoir l’esprit serein au milieu du tumulte, voilà la sagesse.", author: "Marc Aurèle", work: ""},
  {quote: "Ce qui ne tue pas me rend plus fort.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "La fortune ne favorise que les esprits préparés.", author: "Sénèque", work: ""},
  {quote: "Les hommes sont troublés, non par les choses, mais par la manière dont ils les voient.", author: "Épictète", work: ""},
  {quote: "Ce qui compte, ce n’est pas d’ajouter des années à la vie, mais de la vie aux années.", author: "Sénèque", work: ""},
  {quote: "Quand tu es irrité, compte jusqu’à dix avant de parler ; si tu es très en colère, compte jusqu’à cent.", author: "Sénèque", work: ""},
  {quote: "Songe que ce que tu possèdes aujourd’hui appartenait hier à un autre et appartiendra demain à un autre.", author: "Sénèque", work: ""},
  {quote: "On n’est jamais blessé que par soi-même.", author: "Épictète", work: ""},
  {quote: "Accepte tout ce qui t’arrive, tisse en toi la force du destin.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "L’art de vivre ressemble plus à la lutte qu’à la danse.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Sois tolérant avec les autres et strict avec toi-même.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "L’épreuve de la vie, c’est la maîtrise de soi.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Tu as pouvoir sur ton esprit, pas sur les événements extérieurs.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Tout ce que nous entendons est une opinion, non un fait. Tout ce que nous voyons est une perspective, pas la vérité.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "La colère, si elle n’est pas maîtrisée, est fréquemment plus nocive que l’injure qui l’a provoquée.", author: "Sénèque", work: "De la colère"},
  {quote: "Rien n’arrive à l’homme que la nature ne l’ait rendu capable de supporter.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Ce que l’on fait dans la vie résonne dans l’éternité.", author: "Marc Aurèle", work: ""},
  {quote: "Accepte tout ce qui arrive, même si cela semble douloureux, car cela sert ton bien.", author: "Sénèque", work: ""},
  {quote: "La perfection de la morale est d’agir en se conformant à la raison.", author: "Sénèque", work: ""},
  {quote: "La peur est la principale cause de tous nos malheurs.", author: "Sénèque", work: ""},
  {quote: "L’esprit de l’homme est le maître de sa destinée.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Il ne dépend que de toi de voir la beauté de la vie.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "L’homme sage s’adapte aux circonstances, comme l’eau s’adapte au vase.", author: "Sénèque", work: ""},
  {quote: "Un homme heureux est celui qui vit en accord avec sa nature.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Le sage ne s’attriste jamais du passé, ne se laisse pas troubler par l’avenir, il vit dans le présent.", author: "Sénèque", work: ""},
  {quote: "La pauvreté ne vient pas de la diminution des richesses, mais de la multiplication des désirs.", author: "Platon", work: ""},
  {quote: "La nature nous a donné une langue et deux oreilles afin de mieux écouter qu’on ne parle.", author: "Zénon de Cition", work: ""},
  {quote: "Il n’est rien de noble à être supérieur à ses semblables ; la vraie noblesse est d’être supérieur à son ancien moi.", author: "Sénèque", work: ""},
  {quote: "La chance favorise l’esprit préparé.", author: "Sénèque", work: ""},
  {quote: "Pour vivre heureux, vivons cachés.", author: "Épictète", work: ""},
  {quote: "Ce n’est pas la force du vent, mais l’orientation des voiles qui détermine la direction de notre vie.", author: "Sénèque", work: ""},
  {quote: "Le monde est changé par ton exemple, pas par ton opinion.", author: "Sénèque", work: ""},
  {quote: "N’aie rien de plus à cœur que de rester fidèle à toi-même.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Seul le présent nous appartient.", author: "Sénèque", work: ""},
  {quote: "Vivre, ce n’est pas attendre que l’orage passe, c’est apprendre à danser sous la pluie.", author: "Sénèque", work: ""},
  {quote: "Celui qui a commencé a déjà fait la moitié du chemin.", author: "Marc Aurèle", work: ""},
  {quote: "Il faut toute la vie pour apprendre à vivre.", author: "Sénèque", work: "Lettres à Lucilius"},
  {quote: "Fais ce que tu dois, advienne que pourra.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "Celui qui vit en harmonie avec lui-même vit en harmonie avec l’univers.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "La douleur est légère si l’opinion ne l’amplifie pas.", author: "Sénèque", work: ""},
  {quote: "Le bonheur dépend de nous.", author: "Aristote", work: ""},
  {quote: "Le temps découvre la vérité.", author: "Sénèque", work: ""},
  {quote: "La première règle, c’est de se corriger soi-même.", author: "Épictète", work: "Manuel"},
  {quote: "Ne cherche pas à ce que les événements arrivent comme tu le veux, mais veuille les événements comme ils arrivent et tu seras heureux.", author: "Épictète", work: "Manuel"},
  {quote: "Supporte et abstiens-toi.", author: "Épictète", work: ""},
  {quote: "Nul ne peut atteindre l’aube sans passer par le chemin de la nuit.", author: "Khalil Gibran", work: ""},
  {quote: "Agis comme si ce que tu fais fait une différence. Il le fait.", author: "Marc Aurèle", work: ""},
  {quote: "Le contentement apporte la plus grande richesse.", author: "Épictète", work: ""},
  {quote: "L’homme sage n’est jamais esclave du destin.", author: "Sénèque", work: ""},
  {quote: "Ce qui compte, ce n’est pas ce qui nous arrive, mais la manière dont nous y réagissons.", author: "Épictète", work: ""},
  {quote: "Le plus grand obstacle à la vie est l’attente, qui espère demain et néglige aujourd’hui.", author: "Sénèque", work: ""},
  {quote: "Le sage considère l’avenir comme présent.", author: "Sénèque", work: ""},
  {quote: "Sache profiter du présent, car il t’appartient.", author: "Sénèque", work: ""},
  {quote: "Le commencement est la moitié du tout.", author: "Platon", work: ""},
  {quote: "Nul malheur n’est insupportable quand on en fait un gain pour sa vertu.", author: "Sénèque", work: ""},
  {quote: "La vie n’est pas d’attendre que l’orage passe, c’est d’apprendre à danser sous la pluie.", author: "Sénèque", work: ""},
  {quote: "La vertu seule est le but de la vie.", author: "Zénon de Cition", work: ""},
  {quote: "L’homme courageux est libre.", author: "Sénèque", work: ""},
  {quote: "Ce qui est mal, ce n’est pas d’échouer, mais de ne pas essayer.", author: "Sénèque", work: ""},
  {quote: "Fais chaque chose dans la vie comme si c’était la dernière.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "La vie est une pièce de théâtre : ce qui compte, ce n’est pas qu’elle dure longtemps, mais qu’elle soit bien jouée.", author: "Sénèque", work: ""},
  {quote: "Ce n’est pas la nature qui nous trouble, mais nos opinions.", author: "Épictète", work: ""},
  {quote: "Le bonheur est intérieur, pas extérieur.", author: "Sénèque", work: ""},
  {quote: "Le courage n’est pas l’absence de peur, mais la capacité de la vaincre.", author: "Sénèque", work: ""},
  {quote: "Ce n’est pas la force, mais la persévérance qui fait les grandes œuvres.", author: "Samuel Johnson", work: ""},
  {quote: "La sagesse commence dans l’émerveillement.", author: "Socrate", work: ""},
  {quote: "La grandeur d’âme consiste à supporter avec patience les épreuves de la vie.", author: "Marc Aurèle", work: "Pensées pour moi-même"},
  {quote: "La vie est courte, l’art est long.", author: "Hippocrate", work: ""},
  {quote: "Le sage ne s’afflige de rien, il profite de tout.", author: "Sénèque", work: ""},
  {quote: "L’homme est malheureux parce qu’il ne sait pas qu’il est heureux.", author: "Fiodor Dostoïevski", work: ""}
];
